export const Questions = [
    {
        id:1,
        prompt:"Which of the following command is used to install create-react-app?",
        optionA:"npm install -g create-react-app",
        optionB:"npm install create-react-app",
        optionC:"npm install -f create-react-app ",
        optionD:"install -g create-react-app",
        answer:"A",
    },
    {
        id:2,
        prompt:"Which type of JavaScript language is ___?",
        optionA:"Object-Oriented",
        optionB:"Object-Based",
        optionC:"Assembly-language",
        optionD:"High-level",
        answer:"B",
    },
    {
        id:3,
        prompt:"In JavaScript the x===y statement implies that:",
        optionA:"Both x and y are equal in value, type and reference address as well.",
        optionB:"Both are x and y are equal in value only.",
        optionC:"Both are equal in the value and data type.",
        optionD:"Both are not same at all.",
        answer:"C",
    },
    {
        id:4,
        prompt:"Which of the following is an advantage of using JavaScript?",
        optionA:"Less server interaction",
        optionB:"Immediate feedback to the visitors",
        optionC:"Increased interactivity",
        optionD:"All of the above",
        answer:"D",
    },
    {
        id:5,
        prompt:"Which of the following type of variable is visible only within a function where it is defined?",
        optionA:"global variable",
        optionB:"local variable",
        optionC:"Both of the above.",
        optionD:"None of the above",
        answer:"B",
    },
    {
        id:6,
        prompt:"Which of the following function of Boolean object returns a string containing the source of the Boolean object?",
        optionA:"toSource()",
        optionB:"valueOf()",
        optionC:"toString()",
        optionD:"None of the above.",
        answer:"A",
    },
    {
        id:7,
        prompt:"Which of the following function of Array object reverses the order of the elements of an array?",
        optionA:"reverse()",
        optionB:"push()",
        optionC:"reduce()",
        optionD:"reduceRight()",
        answer:"A",
    },
    {
        id:8,
        prompt:"Which of the following is correct about features of JavaScript?",
        optionA:"It can not Handling dates and time.",
        optionB:"JavaScript is a object-based scripting language.",
        optionC:"JavaScript is not interpreter based scripting language.",
        optionD:"All of the above",
        answer:"B",
    },

]